Task 7.4
Ready2112/calculator-kodilla-java pull request #10
Opened 2020-02-25 02:19 UTC by Ready2112

new task - calculate quantity of people in several Countries belonging to correct Continent in the World

2020-02-25 06:27 UTC, MARudnicki requested changes

2020-02-25 06:27 UTC, MARudnicki commented on kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java
> +        BigDecimal bigDecimal = BigDecimal.ZERO;
niewykorzystana zmienna

2020-02-25 06:29 UTC, MARudnicki requested changes

2020-02-25 06:29 UTC, MARudnicki commented on kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java
> +        return countries;
czy na pewno jest senso zeby dodawac kraje z populacja 1, 2, 3 ? Wydaje mi sie, ze to tylko zaciemnia kod. Mozna to zastapic zahardcodowanymi wartosciami. Ewentualnie uzyc ponownie parameters-test

2020-02-25 15:07 UTC, Ready2112 commented on kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java
> +        BigDecimal bigDecimal = BigDecimal.ZERO;
używana w pętli for

2020-02-26 06:37 UTC, MARudnicki commented on kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java
> +        BigDecimal bigDecimal = BigDecimal.ZERO;
ok, moj blad

2020-02-26 18:31 UTC, merged